---
# Ansible Cisco ACI JSON Grabber by James Kayser
# This tool will query your ACI APIC and save the output as a collection of .json files
# main playbook
- hosts: localhost
  gather_facts: false

  vars:
   msg: |
              Check the readme.md file for instructions on how to install and use this script.

              For Password Based Authentication
                 ansible-playbook -i aci_hosts grab-json-aci.yml

  tasks:
    - name: "Remove Existing Working Directory"
      file:
        path: ~/ansible_json_payload
        state: absent
      tags: always

    - name: "Instructions"
      debug:
        msg: "{{ msg.split('\n') }}"
      tags: always             

- hosts: apic
  any_errors_fatal: false

  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python3
 
 
  vars_prompt:

  - name: "apic_ip"
    prompt: "Enter your APIC IP Address"
    private: no

  - name: "user"
    prompt: "Enter your APIC Username  Default"
    private: no
    unsafe: yes
    default: 'admin'

  - name: "pass"
    prompt: "Enter your APIC Password"
    private: yes
    unsafe: yes

  tasks: 

  - name: Pre-processing
    include_tasks: tasks/pre-processing.yml
    tags: always

  - name: Loading Fabric Queries
    include: '{{ item }}'
    with_fileglob:
      - tasks/querydata/*.yml
    tags: always
