---
- name: Make Working Directory
  file:
    path: ~/ansible_json_payload
    state: directory
    mode: '0755'
  register: payload_dir
  tags: always

- name: Grabbing JSON
  include_tasks: grab-json.yml
  loop: '{{ aci_query_list }}'
  loop_control:
    label: '{{ item.aci_query_title }}'
  tags: always
